"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WideAngle = exports.WhiteboardEnhancement = exports.Upgrade = exports.Usb = exports.SpeakerFraming = exports.RecordingQuality = exports.ProductSupport = exports.PortraitLighting = exports.Person = exports.OpenApIs = exports.Microphone = exports.L1OrS1 = exports.ImageQuality = exports.ImageProcessing = exports.IqOrOne = exports.Group = exports.GeniusFraming = exports.GalleryView = exports.Framing = exports.Ethernet = exports.Easy = exports.Document = exports.Contact = exports.Clipboard = exports.BusinessCard = exports.Analytics = void 0;
var Analytics_1 = require("./Analytics");
Object.defineProperty(exports, "Analytics", { enumerable: true, get: function () { return Analytics_1.default; } });
var BusinessCard_1 = require("./BusinessCard");
Object.defineProperty(exports, "BusinessCard", { enumerable: true, get: function () { return BusinessCard_1.default; } });
var Clipboard_1 = require("./Clipboard");
Object.defineProperty(exports, "Clipboard", { enumerable: true, get: function () { return Clipboard_1.default; } });
var Contact_1 = require("./Contact");
Object.defineProperty(exports, "Contact", { enumerable: true, get: function () { return Contact_1.default; } });
var Document_1 = require("./Document");
Object.defineProperty(exports, "Document", { enumerable: true, get: function () { return Document_1.default; } });
var Easy_1 = require("./Easy");
Object.defineProperty(exports, "Easy", { enumerable: true, get: function () { return Easy_1.default; } });
var Ethernet_1 = require("./Ethernet");
Object.defineProperty(exports, "Ethernet", { enumerable: true, get: function () { return Ethernet_1.default; } });
var Framing_1 = require("./Framing");
Object.defineProperty(exports, "Framing", { enumerable: true, get: function () { return Framing_1.default; } });
var GalleryView_1 = require("./GalleryView");
Object.defineProperty(exports, "GalleryView", { enumerable: true, get: function () { return GalleryView_1.default; } });
var GeniusFraming_1 = require("./GeniusFraming");
Object.defineProperty(exports, "GeniusFraming", { enumerable: true, get: function () { return GeniusFraming_1.default; } });
var Group_1 = require("./Group");
Object.defineProperty(exports, "Group", { enumerable: true, get: function () { return Group_1.default; } });
var IqOrOne_1 = require("./IqOrOne");
Object.defineProperty(exports, "IqOrOne", { enumerable: true, get: function () { return IqOrOne_1.default; } });
var ImageProcessing_1 = require("./ImageProcessing");
Object.defineProperty(exports, "ImageProcessing", { enumerable: true, get: function () { return ImageProcessing_1.default; } });
var ImageQuality_1 = require("./ImageQuality");
Object.defineProperty(exports, "ImageQuality", { enumerable: true, get: function () { return ImageQuality_1.default; } });
var L1OrS1_1 = require("./L1OrS1");
Object.defineProperty(exports, "L1OrS1", { enumerable: true, get: function () { return L1OrS1_1.default; } });
var Microphone_1 = require("./Microphone");
Object.defineProperty(exports, "Microphone", { enumerable: true, get: function () { return Microphone_1.default; } });
var OpenApIs_1 = require("./OpenApIs");
Object.defineProperty(exports, "OpenApIs", { enumerable: true, get: function () { return OpenApIs_1.default; } });
var Person_1 = require("./Person");
Object.defineProperty(exports, "Person", { enumerable: true, get: function () { return Person_1.default; } });
var PortraitLighting_1 = require("./PortraitLighting");
Object.defineProperty(exports, "PortraitLighting", { enumerable: true, get: function () { return PortraitLighting_1.default; } });
var ProductSupport_1 = require("./ProductSupport");
Object.defineProperty(exports, "ProductSupport", { enumerable: true, get: function () { return ProductSupport_1.default; } });
var RecordingQuality_1 = require("./RecordingQuality");
Object.defineProperty(exports, "RecordingQuality", { enumerable: true, get: function () { return RecordingQuality_1.default; } });
var SpeakerFraming_1 = require("./SpeakerFraming");
Object.defineProperty(exports, "SpeakerFraming", { enumerable: true, get: function () { return SpeakerFraming_1.default; } });
var Usb_1 = require("./Usb");
Object.defineProperty(exports, "Usb", { enumerable: true, get: function () { return Usb_1.default; } });
var Upgrade_1 = require("./Upgrade");
Object.defineProperty(exports, "Upgrade", { enumerable: true, get: function () { return Upgrade_1.default; } });
var WhiteboardEnhancement_1 = require("./WhiteboardEnhancement");
Object.defineProperty(exports, "WhiteboardEnhancement", { enumerable: true, get: function () { return WhiteboardEnhancement_1.default; } });
var WideAngle_1 = require("./WideAngle");
Object.defineProperty(exports, "WideAngle", { enumerable: true, get: function () { return WideAngle_1.default; } });
